### PR TITLE
Add new functions for Leaflet maps: add_wms_*() and add_wmts_*()

### PR DESCRIPTION
**Pull request by florisvdh**
This adds the following _shortcut functions_ that wrap `addWMSTiles()`, `addWMS()` or `addTiles()` statements to add specific OGC WMS or WMTS layers in Leaflet maps:

afbeelding

They still support the full capabilities of the wrapped functions, through the `...` argument.

May be useful for upcoming coding club too @damianooldoni.

Clearly this can be extended in the future with more shortcut functions as needed. All contributions are welcome!

Some simple examples:

afbeelding

afbeelding

afbeelding

### CODE REVIEW

**Comment by florisvdh** [comment]
It seems that `inbo/actions/check_pkg` doesn't support some R packages because some system dependencies are missing. Best have a look at how [`r-lib/actions/setup-r-dependencies`](https://github.com/r-lib/actions/tree/v2-branch/setup-r-dependencies) tackles the sysdeps by just using `pak::pkg_install()`. It's implemented in https://github.com/r-lib/actions/blob/v2-branch/examples/check-standard.yaml.

**Comment by damianooldoni** [comment]
Nice work, @florisvdh! Indeed, it would be nice to use/show/mention during the next INBO coding club on Aug 31. I have no time at the moment, to check the failing GitHub action. @hansvancalster: could you do, please? Otherwise, I will but later or tomorrow.

**Comment by florisvdh** [comment]
I'm having a look to fix the **lintr** warnings, since those come from my code :smile:.

**Comment by hansvancalster** [comment]
> I'm having a look to fix the **lintr** warnings, since those come from my code 😄.

👍 I also changed the base to v0.0.2 branch. Can you also look at the conflict? I will try to fix the GHA issues in the v0.02 branch.

**Comment by florisvdh** [comment]
> Can you also look at the conflict?

Sure.

**Review by hansvancalster — APPROVED** [review]
Very cool! That makes using wm(t)s with leaflet so much user friendlier. Will it also work with mapview?
Please also add yourself as contributor in DESCRIPTION file.

**Comment by florisvdh** [comment]
> Will it also work with mapview?

Good question. I had a look; the leaflet map object needs to be extracted first, but then it works:

``` r
library(mapview)
#> The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
#> which was just loaded, will retire in October 2023.
#> Please refer to R-spatial evolution reports for details, especially
#> https://r-spatial.org/r/2023/05/15/evolution4.html.
#> It may be desirable to make the sf package available;
#> package maintainers should consider adding sf to Suggests:.
#> The sp package is now running under evolution status 2
#>      (status 2 uses the sf package in place of rgdal)
library(inbospatial)
kmi <- "https://opendata.meteo.be/service/wfs"
kmi_stations <- get_feature_wfs(
  wfs = kmi,
  layer = "synop:synop_station"
)
mapview(kmi_stations) |> add_wms_be_cartoweb()
#> Error in map$x: $ operator not defined for this S4 class
mapview(kmi_stations)@map |> add_wms_be_cartoweb()
```



``` r
mapview(kmi_stations) |> _@map |> add_wms_be_cartoweb()
```



<sup>Created on 2023-08-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I will add this in the examples.

**Comment by florisvdh** [comment]
_Note to self:_

Running **lintr** directly with the **checklist** linter settings can be done as:

```r
options(lintr.linter_file = system.file("lintr", package = "checklist"))
lintr::lint_package()
```

**Comment by hansvancalster** [comment]
> _Note to self:_
> 
> Running **lintr** directly with the **checklist** linter settings can be done as:
> 
> ```r
> options(lintr.linter_file = system.file("lintr", package = "checklist"))
> lintr::lint_package()
> ```

Or use `checklist::check_lintr()` 😉

**Comment by florisvdh** [comment]
Yeah I know, I meant without going through checklist.

**Comment by florisvdh** [comment]
I think this should be good for this PR.

**Pull request merged**
